[provider]
backend = gemini

[gemini]
api_key = AIzaSy-XXXXXXXXXXXXXXX
model = gemma-3-27b-it
context = You are a helpful and friendly bot on IRC.
max_output_tokens = 1000
temperature = 0.8

[openai]
api_key = sk-XXXXXXXXXXXXXXX
model = gpt-4o-mini
context = You are a helpful and friendly bot on IRC.
max_tokens = 1000
temperature = 0.8

[localserver]
target_ip = 127.0.0.1
local_port = 55511
mapping = /v1/chat/completions
context = You are a helpful and friendly bot on IRC.
max_tokens = 1000
temperature = 0.8

[irc]
server = open.ircnet.net
port = 6667
ssl = false
channels = #linux,#github
nickname = MyBot
ident = mybot
realname = My Bot
password =

[tools]
enable_web_search = false
enable_weather = false
enable_image_generation = false
imgbb_api_key =
